spring.application.name=ecom-application
spring.datasource.url=jdbc:postgresql://localhost:5433/ecomdb
spring.datasource.username=rohan
spring.datasource.password=rohan
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
management.endpoints.web.exposure.include=beans,health
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.shutdown.enabled=true
info.app.name= MyNewApp
info.app.description=App built by us
info.app.version=1.0.0
server.shutdown=graceful
spring.h2.console.settings.web-allow-others=true

#create is dangerous for production (just used in development)
