spring.application.name=ecom-application
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
management.endpoints.web.exposure.include=beans,health
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.shutdown.enabled=true
info.app.name= MyNewApp
info.app.description=App built by us
info.app.version=1.0.0
server.shutdown=graceful
spring.h2.console.settings.web-allow-others=true
#create is dangerous for production (just used in development)
